using static NoMercy.Encoder.Format.Rules.Languages;

namespace NoMercy.Encoder.Core;

public class IsoLanguageMapper
{
    public static readonly Dictionary<string, string> IsoToLanguage = new(StringComparer.OrdinalIgnoreCase)
    {
        { Aar, "afar" },
        { Abk, "abkhaz" },
        { Afr, "afrikaans" },
        { Aka, "akan" },
        { Alb, "albanian" },
        { Amh, "amharic" },
        { Ara, "arabic" },
        { Arg, "aragonese" },
        { Arm, "armenian" },
        { Asm, "assamese" },
        { Ava, "avaric" },
        { Ave, "avestan" },
        { Aym, "aymara" },
        { Aze, "azerbaijani" },
        { Bak, "bashkir" },
        { Bam, "bambara" },
        { Baq, "basque" },
        { Bel, "belarusian" },
        { Ben, "bengali" },
        { Bih, "bihari" },
        { Bis, "bislama" },
        { Bos, "bosnian" },
        { Bre, "breton" },
        { Bul, "bulgarian" },
        { Bur, "burmese" },
        { Cat, "catalan" },
        { Cha, "chamorro" },
        { Che, "chechen" },
        { Chi, "chinese" },
        { Chu, "old church slavonic, church slavonic, old bulgarian" },
        { Chv, "chuvash" },
        { Cor, "cornish" },
        { Cos, "corsican" },
        { Cre, "cree" },
        { Cze, "czech" },
        { Dan, "danish" },
        { Div, "divehi, dhivehi, maldivian" },
        { Dut, "dutch" },
        { Dzo, "dzongkha" },
        { Eng, "english" },
        { Epo, "esperanto" },
        { Est, "estonian" },
        { Ewe, "ewe" },
        { Fao, "faroese" },
        { Fij, "fijian" },
        { Fil, "filipino" },
        { Fin, "finnish" },
        { Fre, "french" },
        { Fry, "western frisian" },
        { Ful, "fulah" },
        { Geo, "georgian" },
        { Ger, "german" },
        { Gla, "scottish gaelic, gaelic" },
        { Gle, "irish" },
        { Glg, "galician" },
        { Glv, "manx" },
        { Gre, "greek" },
        { Grn, "guaraní" },
        { Gsw, "swiss german" },
        { Guj, "gujarati" },
        { Hat, "haitian, haitian creole" },
        { Hau, "hausa" },
        { Haw, "hawaiian" },
        { Heb, "hebrew" },
        { Her, "herero" },
        { Hin, "hindi" },
        { Hmo, "hiri motu" },
        { Hrv, "croatian" },
        { Hun, "hungarian" },
        { Ibo, "igbo" },
        { Ice, "icelandic" },
        { Ido, "ido" },
        { Iii, "sichuan yi" },
        { Iku, "inuktitut" },
        { Ile, "interlingue" },
        { Ina, "interlingua" },
        { Ind, "indonesian" },
        { Ipk, "inupiaq" },
        { Ita, "italian" },
        { Jav, "javanese" },
        { Jpn, "japanese" },
        { Kan, "kannada" },
        { Kas, "kashmiri" },
        { Kau, "kanuri" },
        { Kaz, "kazakh" },
        { Khm, "khmer" },
        { Kik, "kikuyu" },
        { Kin, "kinyarwanda" },
        { Kir, "kyrgyz" },
        { Kom, "komi" },
        { Kon, "kongo" },
        { Kor, "korean" },
        { Kua, "kwanyama, kuanyama" },
        { Kur, "kurdish" },
        { Lao, "lao" },
        { Lat, "latin" },
        { Lav, "latvian" },
        { Lim, "limburgish, limburgan, limburger" },
        { Lin, "lingala" },
        { Lit, "lithuanian" },
        { Ltz, "luxembourgish, letzeburgesch" },
        { Lub, "luba-katanga" },
        { Lug, "ganda" },
        { Mac, "macedonian" },
        { Mah, "marshallese" },
        { Mal, "malayalam" },
        { Mao, "māori" },
        { Mar, "marathi" },
        { May, "malay" },
        { Mlg, "malagasy" },
        { Mlt, "maltese" },
        { Mon, "mongolian" },
        { Nau, "nauru" },
        { Nav, "navajo, navaho" },
        { Nbl, "southern ndebele" },
        { Nde, "northern ndebele" },
        { Ndo, "ndonga" },
        { Nep, "nepali" },
        { Nno, "norwegian nynorsk" },
        { Nob, "norwegian bokmål" },
        { Nor, "norwegian" },
        { Nya, "chichewa, chewa, nyanja" },
        { Oci, "occitan" },
        { Oji, "ojibwe, ojibwa" },
        { Ori, "oriya" },
        { Orm, "oromo" },
        { Oss, "ossetian, ossetic" },
        { Pan, "punjabi" },
        { Per, "persian" },
        { Pli, "pāli" },
        { Pol, "polish" },
        { Por, "portuguese" },
        { Pus, "pashto" },
        { Que, "quechua" },
        { Roh, "romansh" },
        { Rum, "romanian" },
        { Run, "kirundi" },
        { Rus, "russian" },
        { Sag, "sango" },
        { San, "sanskrit (saṁskṛta)" },
        { Sin, "sinhala" },
        { Slo, "slovak" },
        { Slv, "slovenian" },
        { Sme, "northern sami" },
        { Smo, "samoan" },
        { Sna, "shona" },
        { Snd, "sindhi" },
        { Som, "somali" },
        { Sot, "southern sotho" },
        { Spa, "spanish" },
        { Srd, "sardinian" },
        { Srp, "serbian" },
        { Ssw, "swati" },
        { Sun, "sundanese" },
        { Swa, "swahili" },
        { Swe, "swedish" },
        { Tah, "tahitian" },
        { Tam, "tamil" },
        { Tat, "tatar" },
        { Tel, "telugu" },
        { Tgk, "tajik" },
        { Tgl, "tagalog" },
        { Tha, "thai" },
        { Tib, "tibetan" },
        { Tir, "tigrinya" },
        { Ton, "tonga" },
        { Tsn, "tswana" },
        { Tso, "tsonga" },
        { Tuk, "turkmen" },
        { Tur, "turkish" },
        { Twi, "twi" },
        { Uig, "uyghur, uighur" },
        { Ukr, "ukrainian" },
        { Urd, "urdu" },
        { Uzb, "uzbek" },
        { Ven, "venda" },
        { Vie, "vietnamese" },
        { Vol, "volapük" },
        { Wel, "welsh" },
        { Wln, "walloon" },
        { Wol, "wolof" },
        { Xho, "xhosa" },
        { Yid, "yiddish" },
        { Yor, "yoruba" },
        { Zha, "zhuang, chuang" },
        { Zul, "zulu" }
    };
}